## McCulloch-Pitts Model

In [1]:
def mcculloch_pitts(inputs, weights, threshold):
    # 檢查輸入數量是否和權重數量相同
    if len(inputs) != len(weights):
        raise ValueError("輸入和權重的數量應該相同")

    # 計算加權和
    weighted_sum = sum([i * w for i, w in zip(inputs, weights)])

    # 決定是否激活神經元
    if weighted_sum >= threshold:
        return 1  # 激活狀態
    else:
        return 0  # 非激活狀態

# 定義輸入、權重和閾值
inputs = [1, 0, 1]
weights = [0.5, -0.5, 0.8]
threshold = 0.2

# 使用模型計算輸出
output = mcculloch_pitts(inputs, weights, threshold)
print("輸出:", output)


輸出: 1


## Competitive Learning

In [5]:
import numpy as np

# 初始化神經元的權重和偏差
num_neurons = 5
input_size = 3
learning_rate = 0.1

# 隨機初始化權重和偏差
weights = np.random.rand(num_neurons, input_size)
bias = np.random.rand(num_neurons)

# 定義競爭學習的訓練函數
def competitive_learning(input_vector):
    global weights, bias

    # 計算輸入向量和每個神經元之間的相似度
    similarity = np.dot(weights, input_vector) + bias

    # 找出最大相似度的神經元的索引
    winning_neuron_idx = np.argmax(similarity)

    # 更新勝出神經元的權重，增加對輸入的響應
    weights[winning_neuron_idx] += learning_rate * (input_vector - weights[winning_neuron_idx])

    return winning_neuron_idx

# 測試一個輸入向量
input_vector = np.array([0.2, 0.4, 0.6])

# 進行競爭學習
winning_neuron_index = competitive_learning(input_vector)
print("Winning neuron index:", winning_neuron_index)
print("Updated weights:", weights)


Winning neuron index: 1
Updated weights: [[0.12498833 0.34383235 0.48869103]
 [0.88936488 0.93922351 0.73147079]
 [0.77514145 0.02247269 0.60057614]
 [0.17174847 0.34130536 0.48491625]
 [0.34959177 0.8198021  0.49721554]]


## Two Layered Recurrent Networks for Competitive Learning

In [4]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import mean_squared_error

# 定義競爭層神經元數量和輸入維度
input_dim = 10
comp_neurons = 5

# 假設 test_data 是你的測試數據
test_data = np.random.rand(10, input_dim)



# 定義輸入層
inputs = tf.keras.Input(shape=(input_dim,))
competition_layer = tf.keras.layers.Dense(comp_neurons, activation='softmax')(inputs)

# 定義反饋層
feedback_layer = tf.keras.layers.Dense(input_dim)(competition_layer)

# 定義整個模型
model = tf.keras.Model(inputs=inputs, outputs=feedback_layer)

# 編譯模型
model.compile(optimizer='adam', loss='mean_squared_error')

# 訓練模型
model.fit(test_data, test_data, epochs=10, batch_size=32)

# 使用模型進行預測
predictions = model.predict(test_data)

# 計算均方根誤差（RMSE）
rmse = np.sqrt(mean_squared_error(test_data, predictions))

# 輸出 RMSE
print("RMSE:", rmse)



Epoch 1/10
1/1 [==============================] - 1s 711ms/step - loss: 0.3473
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3450
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3427
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 0.3403
Epoch 5/10
1/1 [==============================] - 0s 3ms/step - loss: 0.3380
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 0.3357
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 0.3334
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 0.3312
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 0.3289
Epoch 10/10
1/1 [==============================] - 0s 62ms/step
RMSE: 0.5695910164848083
